export { default as HomePage } from "./HomePage";
export { default as LoginPage } from "./LoginPage";
export { default as ErrorPage } from "./ErrorPage";
export { default as ContactPage } from "./ContactPage";
export { default as AboutPage } from "./AboutPage";
export { default as SignupPage } from "./SignupPage";
export { default as CartPage } from "./CartPage";
export { default as WishListPage } from "./WishListPage";
export { default as CheckOutPage } from "./CheckOutPage";
